version: "3.8"
services: 
    web:
        build: .
        ports: 
            - "5000:5000"
        volumes: 
            - .:/code
        environment: 
            FLASK_ENV: development

    redis:
        image: "redis:alpine"