# Generated by Django 3.0.5 on 2020-07-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOperationLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operation_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('ip_address', models.CharField(max_length=100, verbose_name='操作IP地址')),
                ('function_name', models.CharField(max_length=50, verbose_name='功能名称')),
                ('operation_type', models.CharField(choices=[('CREAT', '新增'), ('QUERY', '查询'), ('UPDATE', '修改'), ('DELETE', '删除')], max_length=20, verbose_name='操作类型')),
                ('update_before_value', models.CharField(max_length=20, verbose_name='修改前的值')),
                ('last_after_value', models.CharField(max_length=20, verbose_name='修改后的值')),
                ('operation_status', models.CharField(choices=[('SUCCESS', '成功'), ('FAIL', '失败')], max_length=20, verbose_name='操作状态')),
            ],
            options={
                'verbose_name': '用户操作日志',
                'verbose_name_plural': '用户操作日志',
                'db_table': 'tb_user_operation_log',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='assetdailyreport',
            options={'managed': False, 'verbose_name': '日资产报表', 'verbose_name_plural': '日资产报表'},
        ),
    ]
